### ISSUE TITLE
how to reproduce results in the paper?

### ISSUE THREAD

**Issue by da03** [rosewang2008/language_modeling_via_stochastic_processes#8]
Hi Rose and other authors,

I found your work quite interesting but I'm confused about some details, hope that you can help clarify my confusions:

Are there instructions on how to reproduce results (i.e., numbers in tables) in the paper? I can understand that you cannot share the large trained models, but can you release scripts and instructions for producing the numbers using small models? 

For example, it's not clear to me how you calculated the length mismatch in table 3: in appendix E - Wikisection you said `The length mismatch in % used in Table 3 is calculated with respect to the training set lengths`, but in your code `language_modeling_via_stochastic_processes/transformers/examples/pytorch/text-generation/generation_metrics.py` at lines 308-311, the statistics used for wikisection do not match either the training or the test statistics. Which split did you actually use? Besides, how did you calculate the exact numbers? Did you compare the absolute difference between the **average** section lengths of each section type, or did you compare the absolute difference between the corresponding examples (since for each generation you have a corresponding ground truth where the start of latent variables come from) and then take the average? Did you take the average over all section types to produce a single number? And in the forced long generation, how did you compute the mismatch?

As another example, it is not clear whether the provided generation setting is for the experiments in table 3 or table 4: since no_eos was set in the command, it seems like the forced long generation setting, but then table 4 doesn't use wikisection dataset. Can you clarify which experiment this provided generation command is for?

Lastly, I noticed a seemingly inconsistency between your paper and code: in the paper you said `We first sample a start and end latent, z_0 ∼ p(z_0), z_T ∼ p(z_T ) where p(z_0), p(z_T ) are calculated as the density estimates over the training dataset.` (appendix C.1), but in the code you only sampled z_T from the estimated gaussian on the training set: z_0 is directly taken from the encoded first ground truth sentence: https://github.com/rosewang2008/language_modeling_via_stochastic_processes/blob/main/language_modeling_via_stochastic_processes/transformers/examples/pytorch/text-generation/run_decoding_from_embeddings.py#L371 In fact, the estimated p(z_0) at this line was never used: https://github.com/rosewang2008/language_modeling_via_stochastic_processes/blob/main/language_modeling_via_stochastic_processes/transformers/examples/pytorch/text-generation/run_decoding_from_embeddings.py#L292

Looking forward to your reply!

Thanks,
Yuntian

**Comment by rosewang2008** [comment]
Hi Yuntian,
Thanks for your message and questions! Let me know if you have anymore. Happy to help clarify! 

> Are there instructions on how to reproduce results (i.e., numbers in tables) in the paper? I can understand that you cannot share the large trained models, but can you release scripts and instructions for producing the numbers using small models?

[This file](https://github.com/rosewang2008/nonstationarity/blob/main/language_modeling_via_stochastic_processes/transformers/examples/pytorch/text-generation/final_experiments.sh) should run all the generation results that you're looking for. Let me know if that doesn't address your needs.

Eg. the length mismatch compares the absolute difference between the section length from generation [calculated here](https://github.com/rosewang2008/language_modeling_via_stochastic_processes/blob/main/language_modeling_via_stochastic_processes/transformers/examples/pytorch/text-generation/generation_metrics.py#L164-L181) and the ground truth section length measured [here](https://github.com/rosewang2008/language_modeling_via_stochastic_processes/blob/main/language_modeling_via_stochastic_processes/transformers/examples/pytorch/text-generation/generation_metrics.py#L307). 

> Which split did you actually use?

I used the test split. 

My apologies! The code for generation is quite messy and reflects a lot of the trial-and-error process I had during the project. [The length values in metrics](https://github.com/rosewang2008/language_modeling_via_stochastic_processes/blob/main/language_modeling_via_stochastic_processes/transformers/examples/pytorch/text-generation/generation_metrics.py#L307-L312) should be updated to reflect the numbers reported in the [paper](https://openreview.net/pdf?id=pMQwKL1yctf#page=17). 

I also print the section statistics whenever the datasets get loaded too as a sanity check: https://github.com/rosewang2008/language_modeling_via_stochastic_processes/blob/main/language_modeling_via_stochastic_processes/transformers/src/transformers/data/datasets/language_modeling.py#L626-L627

> Besides, how did you calculate the exact numbers? Did you compare the absolute difference between the average section lengths of each section type, or did you compare the absolute difference between the corresponding examples (since for each generation you have a corresponding ground truth where the start of latent variables come from) and then take the average? Did you take the average over all section types to produce a single number? And in the forced long generation, how did you compute the mismatch?

- I used the absolute difference between avg section lengths and generated. 
- I did average over sections to produce the number in Table 3. 
- IIRC Forced long generation also uses absolute difference since the datasets we used are 'turn-based'/well-sectioned datasets. Any large deviations would indicate the model generates extremely long outputs to account for the forced long-text setting. 

> it is not clear whether the provided generation setting is for the experiments in table 3 or table 4

Running decoding (ie [this script](https://github.com/rosewang2008/language_modeling_via_stochastic_processes/blob/main/language_modeling_via_stochastic_processes/transformers/examples/pytorch/text-generation/run_decoding_from_embeddings.py)) is for both normal and long text generation settings. If for the normal text generation setting, then `--no_eos` should not be True. Otherwise, it should run as described in the README. 

I can try to write up a script for this in the next two weeks, if that's helpful :) 

> Density estimates for generation

The density estimates can be passed into [this function](https://github.com/rosewang2008/language_modeling_via_stochastic_processes/blob/main/language_modeling_via_stochastic_processes/transformers/examples/pytorch/text-generation/run_decoding_from_embeddings.py#L370-L373), but you're right that I'm not doing this by default. I can make that the default in the next changes I push. 

Thanks again for the questions! Let me know if you have any further concerns/q's. 

Best,
Rose

**Comment by da03** [comment]
Hi Rose,

Thanks for answering my questions, that's really helpful!

Best,
Yuntian
